[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='114bbe40d02a5a85a85c2edd10dc882565e134cfc91cc0d2147df86ec4a081bf'
Std = "0x1"
aptos_std = "0x1"


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
